apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-deploy
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: hotel
  template:
    metadata:
      labels:
        app: hotel
    spec:           
      containers:
      - name: hotelapi
        image: kanchanbhong/ezstayhoteladminapi:latest        
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__SqlConnection
          value: "Data Source=mssql;Initial Catalog=HotelsDB;Persist Security Info=True;User ID=sa;Password=Password@123"
          # : - is a sepearater between 
#       - name: Jwt__Secret
#          value: "thisismylengthykeyforencryption"
#        - name: Jwt__Issuer
#          value: "http://identitysvc"
#        - name: Jwt__Audience
#          value: "http://eventsvc"