apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deploy
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:           
      containers:
      - name: identityapi
        image: kanchanbhong/ezstayidentityapi:latest        
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__SqlConnection
          value: "Data Source=mssql;Initial Catalog=EZStay.IdentityDB;Persist Security Info=True;User ID=sa;Password=Password@123"
      #  - name: Jwt__Secret